from : '"#{domain} service"  <noreply@#{domain}>'
subject: You received a payment
content: |
  You received a payment from subscription.

  * Username: #{username}
  * Agreement Type: #{plan}
  * Agreement ID: #{agkey}
  * Gateway: #{gateway}
  * Start Date: #{createdtime}
  * Last Payment: #{lastpay}

