from: '"Kirby from #{domain}" <contact@#{domain}>'
subject: #{domain} - Payment Failed for Your Subscription
content: |
  Hi #{displayname},

  We are here to inform you that the last payment for your #{plan} subscription plan in #{domain} was failed. We didn't receive the fund necessary for the pro plan you are currently using.

  We will try to charge again in the next 2 days, so you may want to verify and update your payment information, which can be found in #{domain}'s billing panel [https://#{domain}/me/billing/](https://#{domain}/me/billing/). The plan will still remain active before the next payment attempt.

  Thank you for your support to #{domain}, for any question please contact contact@#{domain} directly.


  Cheers,
  Kirby
  founder of #{domain}

